# 配置端口
server:
  port: 8861
dubbo:
  # 配置服务信息
  application:
    name: nacos-client
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://tj1-b2c-systech-mione-test03.kscn:80
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: 20880

nacos:
  config:
    addrs: 127.0.0.1:8848

spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true